// Automatically generated by astro-icon
// fd8d4173987d0852d96a5d57e8f824003657e147b38c36ae6d61d5e4158db6ad

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "cib:postgresql"
		| "heroicons-outline:external-link"
		| "heroicons-solid:arrow-sm-left"
		| "heroicons-solid:arrow-sm-right"
		| "mdi:email"
		| "mdi:github"
		| "mdi:linkedin"
		| "simple-icons:github"
		| "simple-icons:linkedin"
		| "simple-icons:django"
		| "simple-icons:sass"
		| "simple-icons:typescript"
		| "astro"
		| "dark"
		| "globe"
		| "light"
		| "preact"
		| "react"
		| "remix"
		| "sanity"
		| "solid"
		| "tailwind";
}