[build]
  command = "npm run build"
  publish = "dist/"

[dev]
  framework = "astro"

[[redirects]]
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok p
  force = true # ensure to always redirect