[build]
  command = "npm run build"
  publish = "dist/"

[dev]
  command = "yarn dev"
  framework = "astro"
  targetPort = 3000

[functions]
  directory = "/netlify/functions"

[[edge_functions]]
  path = "/*"
  function = "theme"